url:          'http://hal.computer'
remote_theme: 'qwtel/hydejack'

title:        'Hal Deployment Platform'

google_fonts:          'Russo One'
font:                  'Russo One', sans-serif;'

accent_image:          ''
accent_color:          '#d84930'
