version: 2

attach_workspace: &attach_workspace
    attach_workspace:
        at: '.'

persist_workspace: &persist_workspace
    persist_to_workspace:
        root: '.'
        paths: [ '.' ]

workflows:

    version: 2

    pipeline:
        jobs:
            - fetch_code:
                filters:
                    branches: { only: ['development'] }
            - install_node_dependencies:
                requires: [ fetch_code ]
            - build_assets:
                requires: [ install_node_dependencies ]
            - build_hugo:
                requires: [ build_assets ]
            - deploy_site:
                requires: [ build_hugo ]

jobs:
    fetch_code:
        working_directory: '~/project'
        docker: [{image: 'circleci/buildpack-deps:jessie'}]
        steps:
            - checkout
            - *persist_workspace

    install_node_dependencies:
        working_directory: '~/project'
        docker: [{image: 'circleci/node:10.4'}]
        steps:
            - *attach_workspace

            - restore_cache:
                keys: [ 'v1-yarn-deps-{{ checksum "yarn.lock" }}', 'v1-yarn-deps' ]

            - run: 'yarn install'

            - save_cache:
                key: 'v1-yarn-deps-{{ checksum "yarn.lock" }}'
                paths: [ 'node_modules' ]

            - *persist_workspace

    build_assets:
        working_directory: '~/project'
        docker: [{image: 'circleci/node:10.4'}]
        steps:
            - *attach_workspace
            - run: 'yarn build'
            - *persist_workspace

    build_hugo:
        working_directory: '~/project'
        docker: [{image: 'felicianotech/docker-hugo:0.41'}]
        steps:
            - *attach_workspace
            - run:
                name: "Run Hugo"
                command: HUGO_ENV=production hugo -v
            - run:
                name: 'debug'
                command: |
                    touch public/.nojekyll
                    echo 'hal.computer' > public/CNAME
                    ls -halR public
            - *persist_workspace

    deploy_site:
        working_directory: '~/project'
        docker: [{image: 'circleci/buildpack-deps:jessie'}]
        steps:
            - *attach_workspace
            - add_ssh_keys:
                fingerprints:
                    - "38:80:64:82:52:6e:80:5e:08:1e:04:54:b6:07:cc:b8"
            - run:
                name: 'Prepare environment'
                command: |
                    mkdir -p ~/.ssh
                    ssh-keyscan github.com > ~/.ssh/known_hosts
                    sudo apt-get install -y rsync
            - run:
                name: 'Deploy'
                command: |
                    git clone ${CIRCLE_REPOSITORY_URL} publish
                    rsync -va --delete --exclude=.git \
                      public/ \
                      publish/

                    cd publish
                    git status
                    git add .

                    git config --global user.email "hal@hal.computer"
                    git config --global user.name "Hal"
                    git commit -m "Building page for ${CIRCLE_SHA1}"

                    git push origin master






